services:
  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: synaps
      POSTGRES_PASSWORD: synaps
      POSTGRES_DB: synaps
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"


volumes:
  pgdata:
